# Form implementation generated from reading ui file '.\ui\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 705)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QHBoxLayout()
        self.header.setObjectName("header")
        self.add_data = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_data.setObjectName("add_data")
        self.header.addWidget(self.add_data)
        self.csv_import = QtWidgets.QPushButton(parent=self.centralwidget)
        self.csv_import.setObjectName("csv_import")
        self.header.addWidget(self.csv_import)
        self.search = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.search.setObjectName("search")
        self.header.addWidget(self.search)
        self.user_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.user_name.setObjectName("user_name")
        self.header.addWidget(self.user_name)
        self.verticalLayout_2.addLayout(self.header)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.list_passwords = QtWidgets.QLabel(parent=self.centralwidget)
        self.list_passwords.setObjectName("list_passwords")
        self.verticalLayout.addWidget(self.list_passwords)
        self.table_passwords = QtWidgets.QTableView(parent=self.centralwidget)
        self.table_passwords.setAcceptDrops(False)
        self.table_passwords.setAlternatingRowColors(False)
        self.table_passwords.setObjectName("table_passwords")
        self.verticalLayout.addWidget(self.table_passwords)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_data.setText(_translate("MainWindow", "+"))
        self.csv_import.setText(_translate("MainWindow", " ↓"))
        self.user_name.setText(_translate("MainWindow", "TextLabel"))
        self.list_passwords.setText(_translate("MainWindow", "Список паролей"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
